clone_depth: 1

environment:
    matrix:
        - MINGW_VERSION: mingw32
          ARCH: i686
        - MINGW_VERSION: mingw64
          ARCH: x86_64

matrix:
    fast_finish: true

build_script:
    - cd C:\projects\gnuradio-mingw
    - C:\msys64\usr\bin\bash build.sh
    - appveyor PushArtifact c:\projects\gnuradio-mingw\dependencies.txt
    - appveyor PushArtifact c:\projects\gnuradio-mingw\gnuradio-%MINGW_VERSION%.tar.xz
